[general]
vendor=M5Stack
name=Tab5,Tab5 v1.1

[hardware]
target=ESP32P4
flashSize=16MB
spiRam=true
spiRamMode=OCT
spiRamSpeed=120M
tinyUsb=true
esptoolFlashFreq=120M

[display]
size=5"
shape=rectangle
dpi=187

[lvgl]
colorDepth=16
